// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy18FvlQjMgohbGxoiVK7Vu1xwTKhpCRQ',
    appId: '1:690934784706:web:9cd723b32e7780536f915b',
    messagingSenderId: '690934784706',
    projectId: 'employmentapp-3c2c2',
    authDomain: 'employmentapp-3c2c2.firebaseapp.com',
    storageBucket: 'employmentapp-3c2c2.firebasestorage.app',
    measurementId: 'G-K2PR33XKL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQTUbD45LsSX-D9y5rLE_zF7T7jOEp3bQ',
    appId: '1:690934784706:android:d8833d66d5343c246f915b',
    messagingSenderId: '690934784706',
    projectId: 'employmentapp-3c2c2',
    storageBucket: 'employmentapp-3c2c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCDpCrpcYNu6YUrbfE_pVOI-lDF_pOUak',
    appId: '1:690934784706:ios:8e8c1c275f7afcf66f915b',
    messagingSenderId: '690934784706',
    projectId: 'employmentapp-3c2c2',
    storageBucket: 'employmentapp-3c2c2.firebasestorage.app',
    iosBundleId: 'com.example.employmentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCDpCrpcYNu6YUrbfE_pVOI-lDF_pOUak',
    appId: '1:690934784706:ios:8e8c1c275f7afcf66f915b',
    messagingSenderId: '690934784706',
    projectId: 'employmentapp-3c2c2',
    storageBucket: 'employmentapp-3c2c2.firebasestorage.app',
    iosBundleId: 'com.example.employmentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy18FvlQjMgohbGxoiVK7Vu1xwTKhpCRQ',
    appId: '1:690934784706:web:76f656dbe657ea9b6f915b',
    messagingSenderId: '690934784706',
    projectId: 'employmentapp-3c2c2',
    authDomain: 'employmentapp-3c2c2.firebaseapp.com',
    storageBucket: 'employmentapp-3c2c2.firebasestorage.app',
    measurementId: 'G-8PLV0CL0ME',
  );

}